cohort_name = "covid-19"

path = "/Users/babylon/Documents/Covid/Data/"
data_path = "/Users/babylon/Documents/Data/KCHData/"
stats_path = "/Users/babylon/Documents/Data/KCHData/Stats/"
prediction_path = "/Users/babylon/Documents/Covid/Figures/Prediction/"
clustering_path = "/Users/babylon/Documents/Data/KCHData/ClusteringData/"
clustered_timeseries_path = "/Users/babylon/Documents/Data/KCHData/ClusteredTimeSeries/"
lstm_prediction_path = "/Users/babylon/Documents/Covid/Figures/Prediction/LSTM"
lstm_stats_path = "/Users/babylon/Documents/Data/KCHData/Stats/LSTM"
lstm_model_path = "/Users/babylon/Documents/Data/KCHData/Models/LSTM"
